import { Button } from '@/components/Button'
import Head from 'next/head'
import Image from 'next/image'
import siginBackground from '../assets/login.svg'
import { FormWrapper, ImageContainer, SignInContainer } from '@/styles/pages/signIn'
import { Input } from '@/components/Input'


export default function Home() {
  return (
    <>
      <Head>
        <title>Presente Surpresa</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SignInContainer>
        <ImageContainer>
          <Image src={siginBackground} width={520} height={480} alt="" />
        </ImageContainer>
        <FormWrapper>
          <h1>
            Não envie brindes, <br />
            crie experiências! 🚀
          </h1>

          <p>
            Faça a gestão de todos os seus brindes <br />
            e produtos personalizados de maneira <br />
            mais simples na nossa plataforma! 🧡
          </p>

          <form>
            <Input placeholder='Nome' />
            <Input placeholder='E-mail' />
            <Button title="Entrar" type='submit' />
          </form>
        </FormWrapper>
      </SignInContainer>
    </>
  )
}
